name: Auto release minor version

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  bump-and-release:
    # Skip when the push is the automated release commit itself
    if: github.event.head_commit.message != null && !startsWith(github.event.head_commit.message, 'chore(release):')
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: "20"
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Bump minor version
        id: version
        run: |
          tag=$(npm version minor -m "chore(release): %s")
          echo "tag=$tag" >> "$GITHUB_OUTPUT"

      - name: Push release commit and tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin HEAD --follow-tags

      - name: Create GitHub release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if gh release view "${{ steps.version.outputs.tag }}" > /dev/null 2>&1; then
            echo "Release ${{ steps.version.outputs.tag }} already exists; skipping creation."
          else
            gh release create "${{ steps.version.outputs.tag }}" --generate-notes
          fi
